version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /examples/vercel-ai-sdk
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /examples/langgraph
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /examples/mcp-client
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
